add loading popup
BalticAmadeus/ProPeek pull request #147
Opened 2024-01-31 14:40 UTC by mmarkauskas

2024-02-01 09:34 UTC, PauliusKu requested changes

2024-02-01 09:34 UTC, PauliusKu commented on src/webview/ProfilerViewer.ts
> +                        console.log(showStartTime, "Switchhhhhhhhhhhhh");
Remove logging

2024-02-01 09:34 UTC, PauliusKu commented on src/view/app/FlameGraph/profilerFlameGraph.tsx
> +    showStartTime = event.target.value === "Combined" ? false : true;
reduce to `showStartTime = event.target.value !== "Combined";`

2024-02-01 10:01 UTC, abelzis approved these changes

2024-02-02 08:58 UTC, PauliusKu approved these changes

2024-02-02 08:58 UTC, merged